//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccp
    {
        public int CCP_id { get; set; }
        public string Sec_id { get; set; }
        public string Offence { get; set; }
        public string Arrestable { get; set; }
        public string warrentable { get; set; }
        public string bailable { get; set; }
        public string Compoundable { get; set; }
        public string punishment { get; set; }
        public string tryable_court { get; set; }
        public Nullable<int> crime_cat_id { get; set; }
    
        public virtual law_catagry law_catagry { get; set; }
    }
}
