//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citation
    {
        public int CITATION_ID { get; set; }
        public string CAT_ID { get; set; }
        public string TITLE { get; set; }
        public string DETAIL { get; set; }
        public string COMPLAINENT_NAME { get; set; }
        public string SUSPECTED_NAME { get; set; }
        public Nullable<int> RESULT { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
    }
}
