//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public int City_Id { get; set; }
        public string City_Name { get; set; }
        public string Province_Name { get; set; }
        public Nullable<int> State_id { get; set; }
    
        public virtual state state { get; set; }
    }
}
