//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image_slider
    {
        public int IMAGE_ID { get; set; }
        public string Name { get; set; }
        public string TITLE { get; set; }
        public string DETAIL { get; set; }
        public string PATH { get; set; }
        public string ACTION { get; set; }
    }
}
