//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class law_catagry
    {
        public law_catagry()
        {
            this.case_exmpl = new HashSet<case_exmpl>();
            this.ccps = new HashSet<ccp>();
            this.lwr_catgry = new HashSet<lwr_catgry>();
        }
    
        public int Law_cat_id { get; set; }
        public string catgry_name { get; set; }
    
        public virtual ICollection<case_exmpl> case_exmpl { get; set; }
        public virtual ICollection<ccp> ccps { get; set; }
        public virtual ICollection<lwr_catgry> lwr_catgry { get; set; }
    }
}
