//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class lawyer
    {
        public lawyer()
        {
            this.case_exmpl = new HashSet<case_exmpl>();
            this.lwr_catgry = new HashSet<lwr_catgry>();
        }
    
        public int lwr_id { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Area { get; set; }
        public string Experience { get; set; }
        public string court_Level { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }
        public string Phone_No { get; set; }
        public string photo { get; set; }
        public string Address { get; set; }
        public string Vision { get; set; }
        public string Objective { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string VERIFY_CODE { get; set; }
    
        public virtual ICollection<case_exmpl> case_exmpl { get; set; }
        public virtual ICollection<lwr_catgry> lwr_catgry { get; set; }
    }
}
