//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int news_id { get; set; }
        public string Title { get; set; }
        public string discription { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string Summary { get; set; }
    }
}
