//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pladbEntities : DbContext
    {
        public pladbEntities()
            : base("name=pladbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<book> books { get; set; }
        public DbSet<case_exmpl> case_exmpl { get; set; }
        public DbSet<ccp> ccps { get; set; }
        public DbSet<city> cities { get; set; }
        public DbSet<civil_law_panel> civil_law_panel { get; set; }
        public DbSet<law_catagry> law_catagry { get; set; }
        public DbSet<lwr_catgry> lwr_catgry { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<state> states { get; set; }
        public DbSet<citation> citations { get; set; }
        public DbSet<lawyer> lawyers { get; set; }
        public DbSet<image_slider> image_slider { get; set; }
    }
}
