//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakLawAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.cities = new HashSet<city>();
        }
    
        public int State_id { get; set; }
        public string State_Name { get; set; }
    
        public virtual ICollection<city> cities { get; set; }
    }
}
